# Generated by Django 4.2 on 2023-06-01 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2', models.CharField(max_length=77)),
                ('p1', models.TextField(verbose_name='First Paragraph')),
                ('p2', models.TextField(verbose_name='Second Paragraph')),
                ('document', models.FileField(upload_to='pdf', verbose_name='WHITEPAPER')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=77)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeSecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=77, verbose_name='SECOND TITLE')),
                ('speech', models.TextField(verbose_name='SECOND SPEECH')),
            ],
        ),
        migrations.CreateModel(
            name='HomeThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='home')),
                ('title', models.CharField(max_length=77, verbose_name='SECOND SPEECH')),
            ],
        ),
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='team')),
                ('name', models.CharField(max_length=77)),
                ('des', models.CharField(max_length=77, verbose_name='DESIGNATION')),
                ('fb_URL', models.URLField(blank=True, null=True, verbose_name='FACEBOOK URL')),
                ('tw_URL', models.URLField(blank=True, null=True, verbose_name='TWITTER URL')),
                ('lk_URL', models.URLField(blank=True, null=True, verbose_name='LINKEDIN URL')),
                ('insta_URL', models.URLField(blank=True, null=True, verbose_name='INSTAGRAM URL')),
            ],
        ),
        migrations.CreateModel(
            name='TK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('speech', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'TOKENIZE',
            },
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wel_title', models.CharField(max_length=77, verbose_name='WELCOME SPEECH TITLE')),
                ('wel_speech', models.TextField(verbose_name='WELCOME SPEECH')),
            ],
        ),
    ]
