# Generated by Django 4.2 on 2023-06-07 08:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ews_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newletter',
            new_name='News',
        ),
        migrations.AlterModelOptions(
            name='homesecondsection',
            options={'verbose_name_plural': 'INVESTMENT SPEECH'},
        ),
        migrations.AlterModelOptions(
            name='homethird',
            options={'verbose_name_plural': 'SHACKLES'},
        ),
        migrations.AlterField(
            model_name='about',
            name='document',
            field=models.FileField(upload_to='media/pdf', verbose_name='WHITEPAPER'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='ews_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
