# Generated by Django 4.2 on 2023-06-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ews_app', '0004_tokenvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenvideo',
            name='name',
            field=models.CharField(default='glory', max_length=12),
            preserve_default=False,
        ),
    ]
