from django.urls import path
from ews_app import views

app_name = 'ews_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('TOKEN_SALES/', views.token, name='ts'),
    path('Contact/', views.contact, name='contact'),
    path('Frequently_asked_questions/', views.faq, name='faq'),
    path('RoadMap/', views.roadmap, name='road'),
    path('Team/', views.team, name='team'),
    path('sign-UP/', views.register_user, name='register'),
    path('login_user', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('HOME/', views.AdminHome, name='ad-hm'),
    path('delete/<speech_id>', views.DeleteWelcome, name='delete_welcome'),
    path('update/Welcome/<str:pk>', views.UpdateWelcome, name='update_welcome'),
    path('Welcome_LIST/', views.WelcomeList, name='wl'),
    path('CREATE_WELCOME/', views.AdminWelcome, name='create-welcome'),
    path('Invest_LIST/', views.InvestList, name='il'),
    path('CREATE_INVESTMENT/', views.AdminInvestment, name='create-invest'),
    path('update/Invest/<invest_pk>', views.UpdateInvestment, name='update_invest'),
    path('delete/invest/<invest_pk>', views.DeleteInvestment, name='delete_invest'),
    path('Third_LIST/', views.HomeThirdView, name='tl'),
    path('CREATE_THIRD/', views.CreateHomeThird, name='create-third'),
    path('EDIT_THIRD/<str:pk>', views.editHomeThird, name='edit-third'),
    path('delete/THIRD/<str:pk>', views.deleteHomeThirdSection, name='delete-third'),
    path('About_LIST/', views.aboutList, name='admin-about'),
    path('CREATE_About/', views.CreateAbout, name='create-about'),
    path('EDIT_ABOUT/<str:pk>', views.editAbout, name='edit-about'),
    path('delete/ABOUT/<str:pk>', views.deleteAbout, name='delete-about'),
    path('TOKENIZE_LIST/', views.Tokenize, name='token'),
    path('CREATE_Token/', views.TokenCreate, name='create-token'),
    path('EDIT_Token/<str:pk>', views.editToken, name='edit-token'),
    path('delete/TOKENIZE/<token_pk>', views.deleteTokenHome, name='token-delete'),
    # path('CREATE_TokenVideo/', views.tokenVid, name='create-tkv'),
    path('ADMIN_FAQ', views.AdminFaq, name='faq-admin'),
    path('CREATE_FAQ/', views.CreateAdminFaq, name='create-faq'),
    path('EDIT_FAQ/<str:pk>', views.editFaq, name='edit-faq'),
    path('delete_FAQ/<str:pk>', views.deleteFaq, name='delete-faq'),
    path('contactAdmin/', views.contactAdmin, name='contactAdmin'),
    path('delete_Contact/<str:pk>', views.deleteContact, name='delete-contact'),
    path('profile/<int:pk>', views.profile, name='profile'),
    path('Update_my_Profile/', views.update_user, name='update_user'),
    path('ROADMAP-ADMIN/', views.AdminRMap, name='roadList'),
    path('CREATE-ROADMAP/', views.CreateMap, name='create_map'),
    path('EDIT-ROADMAP/<str:pk>', views.EditCreateMap, name='edit_create_map'),
    path('DELETE_ROADMAP/<str:pk>', views.deleteCreateMap, name='delete_create_map'),
    path('CREATE-ROADMAP-RIGHT/', views.RoadmapRight1, name='create_map_R'),
    path('EDIT-ROADMAP-RIGHT/<str:pk>', views.EditRoadmapRight1, name='edit_create_map_R'),
    path('DELETE_ROADMAP-RIGHT/<str:pk>', views.deleteRoadmapR1, name='delete_road_map_R'),
    path('CREATE-ROADMAP-LEFT/', views.RoadmapLeft1, name='create_map_L'),
    path('EDIT-ROADMAP-LEFT/<str:pk>', views.EditRoadmapLeft1, name='edit_create_map_L'),
    path('DELETE_ROADMAP-LEFT/<str:pk>', views.deleteRoadmapLeft1, name='delete_road_map_L'),
    path('CREATE-ROADMAP-RIGHT-TWO/', views.RoadmapRight2, name='create_map_Rt'),
    path('EDIT-ROADMAP-RIGHT-TWO/<str:pk>', views.EditRoadmapRight2, name='edit_create_map_Rt'),
    path('DELETE_ROADMAP-RIGHT-TWO/<str:pk>', views.deleteRoadmapRight2, name='delete_road_map_Rt'),
    path('CREATE-ROADMAP-LEFT-TWO/', views.RoadmapLeft2, name='create_map_Lt'),
    path('EDIT-ROADMAP-LEFT-TWO/<str:pk>', views.EditRoadmapLeft2, name='edit_create_map_Lt'),
    path('DELETE_ROADMAP-LEFT-TWO/<str:pk>', views.deleteRoadmapLeft2, name='delete_road_map_Lt'),

]
